---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ .IDENTITY_SERVICE_API_NAME }}
  labels:
    cert-manager.io/solver: http01
  annotations:
    cert-manager.io/enabled: "true"
    kubernetes.io/ingress.class: "nginx-external"
    ingress.kubernetes.io/backend-protocol: "HTTPS"
    ingress.kubernetes.io/force-ssl-redirect: "true"
    ingress.kubernetes.io/proxy-send-timeout: "3600"
    ingress.kubernetes.io/proxy-read-timeout: "3600"
spec:
  rules:
    - host: {{.IDENTIY_SERVICE_API_URL}}
      http:
        paths:
          - backend:
              serviceName: {{ .IDENTITY_SERVICE_API_NAME }}
              servicePort: 8443
            path: /
  tls:
    - hosts:
        - {{.IDENTIY_SERVICE_API_URL}}
      secretName: {{.IDENTIY_SERVICE_API_URL}}-cmio
